// <auto-generated />
using System;
using BusinessApp.Test;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BusinessApp.Test.Shared.Migrations
{
    [DbContext(typeof(BusinessAppTestDbContext))]
    partial class BusinessAppTestDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BusinessApp.Test.ChildResponseStub", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ResponseStubId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResponseStubId");

                    b.ToTable("ChildResponseStub");
                });

            modelBuilder.Entity("BusinessApp.Test.AggregateRootStub", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("AggregateRootStub");
                });

            modelBuilder.Entity("BusinessApp.Test.DomainEventStub", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("DomainEventStub");
                });

            modelBuilder.Entity("BusinessApp.Test.ResponseStub", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ResponseStubId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResponseStubId");

                    b.ToTable("ResponseStub");
                });

            modelBuilder.Entity("BusinessApp.Test.ChildResponseStub", b =>
                {
                    b.HasOne("BusinessApp.Test.ResponseStub", "ResponseStub")
                        .WithMany()
                        .HasForeignKey("ResponseStubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BusinessApp.Test.ResponseStub", b =>
                {
                    b.HasOne("BusinessApp.Test.ResponseStub", null)
                        .WithMany("ChildResponseStubs")
                        .HasForeignKey("ResponseStubId");
                });
#pragma warning restore 612, 618
        }
    }
}
