version: "2.4"

services:
  $(lower_appname):
    build:
      context: .
      dockerfile: Dockerfile.development
      args:
        USER__CA_CERT: "${USER__CA_CERT?}"
        CONTAINER__EXTRA_DEPS: "${CONTAINER__EXTRA_DEPS}"
    image:  projects/$(lower_appname)/webapi:dev
    # map the app and some other commong "nice to have files"
    volumes:
      - .:/home/dotnet/$(lower_appname)
      - ${HOME}/.bash_aliases:/home/dotnet/.bash_aliases
      - ${HOME}/.bash_history:/home/dotnet/.bash_history
      - ${HOME}/.bash_profile:/home/dotnet/.bash_profile
      - ${HOME}/.bashrc:/home/dotnet/.bashrc
      - ${HOME}/.profile:/home/dotnet/.profile
      - ${HOME}/.gitconfig:/home/dotnet/.gitconfig
      - ${HOME}/.git_template:/home/dotnet/.git_template
      - ${HOME}/.vim:/home/dotnet/.vim
    ports:
      - "${$(upper_appname)_WEBAPI__HTTP_PORT?}:5000"
      - "${$(upper_appname)_WEBAPI__HTTPS_PORT?}:5001"
    environment:
      - TERM=xterm-256color
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5000;http://0.0.0.0:5001
      - $(upper_appname)_CONNECTIONSTRINGS__MAIN=${$(upper_appname)_CONNECTIONSTRINGS__MAIN?}
      - $(upper_appname)_CONNECTIONSTRINGS__DBTEST=${$(upper_appname)_CONNECTIONSTRINGS__DBTEST?}
      - $(upper_appname)_TEST_CONNECTIONSTRINGS__MAIN=${$(upper_appname)_TEST_CONNECTIONSTRINGS__MAIN?}
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "${$(upper_appname)_DB__SAPASSWORD?}"
      ACCEPT_EULA: "Y"
    ports:
      - "${$(upper_appname)_DB__PORT?}:1433"
