version: "2.4"

services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile.development
    image:  projects/$(lower_appname)/webapi:dev
    command: dotnet watch run
    volumes:
      - .:/webapi
    ports:
      - "${$(upper_appname)_WEBAPI__HTTP_PORT?}:5000"
      - "${$(upper_appname)_WEBAPI__HTTPS_PORT?}:5001"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      $(upper_appname)_CONNECTIONSTRINGS__MAIN: "${$(upper_appname)_CONNECTIONSTRINGS__MAIN?}"
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "${$(upper_appname)_DB__SAPASSWORD?}"
      ACCEPT_EULA: "Y"
    ports:
      - "${$(upper_appname)_DB__PORT?}:1433"
