// <auto-generated />
using System;
using BusinessApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BusinessApp.Data.Migrations
{
    [DbContext(typeof(BusinessAppDbContext))]
    [Migration("20201204212724_CreateEventMetadata")]
    partial class CreateEventMetadata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("Relational:Sequence:evt.EventIds", "'EventIds', 'evt', '1', '1', '', '', 'Int64', 'False'")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BusinessApp.Data.EventMetadata", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("EventMetadataId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CorrelationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("NEXT VALUE FOR evt.EventIds");

                    b.Property<string>("EventCreator")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("EventDisplayText")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<DateTimeOffset>("OccurredUtc")
                        .HasColumnType("datetimeoffset(0)");

                    b.HasKey("Id");

                    b.ToTable("EventMetadata","evt");
                });
#pragma warning restore 612, 618
        }
    }
}
