# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- releases/all-features

pr:
- releases/all-features

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'DEBUG'
  GitVersion.SemVer: ''
  testProjects: '**/*Test.csproj'

steps:
  - task: gitversion/setup@0
    displayName: Install GitVersion
    inputs:
      versionSpec: "5.3.7"

  - task: gitversion/execute@0
    displayName: Use GitVersion
    inputs:
      useConfigFile: true
      configFilePath: "GitVersion.yml"

  - script: |
      echo FullSemVer: $(fullSemVer)
      echo ##vso[build.updatebuildnumber]$(fullSemVer)
    displayName: 'Update build number'

  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '5.0.x'

  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: '**/*.sln'

  - task: DotNetCoreCLI@2
    displayName: 'Base Build'
    inputs:
      command: build
      projects: '**/*.sln'
      versioningScheme: byBuildNumber

  - task: DotNetCoreCLI@2
    displayName: 'Build EFCore'
    inputs:
      command: build
      projects: '**/*.sln'
      versioningScheme: byBuildNumber
      arguments: '-p:DefineConstants=efcore%3B$(buildConfiguration)'

  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: test
      # XXX do not target solution, we need the data integrations tests to run
      # before the functional tests or else the test databsae will not be there
      # since there is a compiler directive to build the DB with efcore and running
      # the test with DefineConstants does not work
      projects: '$(testProjects)'
