# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  GitVersion.SemVer: ''
  testProjects: '**/*Test.csproj'
  runtimeProjects: '**/*.csproj'

steps:
- task: gittools.gitversion.gitversion-task.GitVersion@5
  displayName: GitVersion

- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '$(runtimeProjects)'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: '$(runtimeProjects)'
    arguments: '--configuration $(buildConfiguration) -p:DefineConstants=dataannotations%3Befcore%3Bfluentvalidation%3Bjson%3Bdocker'


- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: '$(testProjects)'
    arguments: '--configuration $(buildConfiguration)'
