# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  GitVersion.SemVer: ''
  testProjects: '**/*Test.csproj'

steps:
  - task: gittools.gitversion.gitversion-task.GitVersion@5
    displayName: GitVersion

  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '5.0.x'

  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: '**/*.sln'

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: '**/*.sln'
      configuration: '$(buildConfiguration)'
      versioningScheme: byBuildNumber
      arguments: '-p:DefineConstants=dataannotations%2Befcore%3Bfluentvalidation%3Bdocker'

  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: test
      projects: '$(testProjects)'
