version: "2.4"

services:
  dotnet-sln-template:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER__CA_CERT: "${USER__CA_CERT?}"
        CONTAINER__EXTRA_DEPS: "${CONTAINER__EXTRA_DEPS}"
    image:  projects/dotnet-sln-template:dev
    volumes:
      - .:/home/dotnet/dotnet-sln-template
      - ${HOME}/.bash_aliases:/home/dotnet/.bash_aliases
      - ${HOME}/.bash_history:/home/dotnet/.bash_history
      - ${HOME}/.bash_profile:/home/dotnet/.bash_profile
      - ${HOME}/.bashrc:/home/dotnet/.bashrc
      - ${HOME}/.profile:/home/dotnet/.profile
      - ${HOME}/.gitconfig:/home/dotnet/.gitconfig
      - ${HOME}/.git_template:/home/dotnet/.git_template
      - ${HOME}/.vim:/home/dotnet/.vim
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - TERM=xterm-256color
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5000;http://0.0.0.0:5001
      - CONNECTIONSTRINGS__MAIN=Server=db;User Id=sa;Password=dfGhaj76Kjdh82983;Initial Catalog=BusinessApp
