version: "2.4"

services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile.development
    image:  projects/static-forms/webapi:dev
    command: dotnet watch run
    volumes:
      - .:/src
    ports:
      - "8080:80"
      - "8081:443"
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "foobar123@!3A"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
