version: "3"
networks:
    static_network:
        ipam:
            driver: default
            config:
                - subnet: 172.20.0.0/16
services:
    api:
        build: .
        ports:
            - "8080:80"
            - "8081:443"
        depends_on:
            - db
        networks:
            - static_network
    db:
        image: "microsoft/mssql-server-windows-express"
        environment:
            SA_PASSWORD: "foobar123@!3A"
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"
        networks:
            static_network:
                ipv4_address: 172.20.128.2
