FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build

COPY *.crt /usr/local/share/ca-certificates/
RUN apt-get update
RUN apt-get install -y ca-certificates
RUN update-ca-certificates

# Just copy everything since we need to preserve dir structure & there is no other way to do it
WORKDIR /src
COPY . .
RUN dotnet restore

WORKDIR /src/BusinessApp.WebApi
CMD ["dotnet", "run"]
