# do not forget to add a .env file
version: "3.9"

services:
  webapi:
    build:
      context: .
      args:
        $(upper_appname)_CONNECTIONSTRINGS__MAIN: "${$(upper_appname)_CONNECTIONSTRINGS__MAIN?}"
    image:  projects/$(lower_appname)/webapi:latest
    ports:
      - "${$(upper_appname)_WEBAPI__HTTP_PORT?}:80"
      - "${$(upper_appname)_WEBAPI__HTTPS_PORT?}:443"
    environment:
      $(upper_appname)_CONNECTIONSTRINGS__MAIN: "${$(upper_appname)_CONNECTIONSTRINGS__MAIN?}"
    restart: always
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    restart: always
    environment:
      SA_PASSWORD: "${$(upper_appname)_DB__SAPASSWORD?}"
      ACCEPT_EULA: "Y"
    ports:
      - "${$(upper_appname)_DB__PORT?}:1433"
